language switcher

diff --git a/bin/atcoder b/bin/atcoder
--- a/bin/atcoder
+++ b/bin/atcoder
@@ -9,20 +9,25 @@ CURLCMD=(
 		-c "$COOKIE_JAR"
 )
 
+# custom parameters
+declare -f atcoder_build
 declare -f atcoder_run
 declare SOURCETMPL
 declare SOURCEFILE
 declare LANGUAGEID
 
 atcoder_assert_config() {
+	type -t atcoder_build >/dev/null || exitm "config missing: atcoder_build"
 	type -t atcoder_run >/dev/null || exitm "config missing: atcoder_run"
 	[ -v SOURCETMPL ] || exitm "config missing: SOURCETMPL"
 	[ -v SOURCEFILE ] || exitm "config missing: SOURCEFILE"
 	[ -v LANGUAGEID ] || exitm "config missing: LANGUAGEID"
 }
 
-[ ! -x ~/.atcoder ] || . ~/.atcoder
-[ ! -x ./.atcoder ] || . ./.atcoder
+atcoder_load_config() {
+	[ ! -x ~/.atcoder ] || . ~/.atcoder
+	[ ! -x ./.atcoder ] || . ./.atcoder
+}
 
 # common functions
 exitm() {
@@ -162,8 +167,8 @@ atcoder_detect_by_pwd() {
 	pwd | atcoder_detect_by_dir "$@"
 }
 
-declare CONTEST PROBLEM
-
+declare CONTEST
+declare PROBLEM
 atcoder_assert_pwd() {
 	CONTEST="$(atcoder_detect_by_pwd CONTEST)"
 	PROBLEM="$(atcoder_detect_by_pwd PROBLEM)"
@@ -258,9 +263,19 @@ checked_cp() {
 	local CPFROM="$1"
 	local CPTO="$2"
 
-	# `cp -i` don't fail even if overwrite cancelled interactively.
 	[ -f "${CPFROM}" ] || exitm "cannoct access to template: $CPFROM"
 
+	m cp "$CPFROM" "$CPTO"
+	cp "$CPFROM" "$CPTO" || exitm "cp faield."
+}
+
+checked_cp_i() {
+	local CPFROM="$1"
+	local CPTO="$2"
+
+	[ -f "${CPFROM}" ] || exitm "cannoct access to template: $CPFROM"
+
+	# `cp -i` don't fail even if overwrite cancelled interactively.
 	if [ -e "$CPTO" ]
 	then
 		echo 1>&2 -n "$CPTO already exists. Overwrite? [y/N]"
@@ -286,22 +301,46 @@ checked_cp() {
 	cp "$CPFROM" "$CPTO" || exitm "cp faield."
 }
 
-atcoder_do_init() {
-	local WORKROOT
+declare WORKROOT
+atcoder_assert_git() {
+	local RC
 	WORKROOT="$(git rev-parse --show-toplevel)"
 	RC="$?"
 	case "$RC" in
-	0)
-		;;
-	*)
-		exitm "Failed to detect WORKROOT($RC). Please check if git repo is properly checked out."
-		;;
+	0) ;;
+	*) exitm "Failed to detect WORKROOT($RC). Please check if git repo is properly checked out." ;;
 	esac
+}
 
+atcoder_do_init() {
+	local ATCODER_LANG="$1"
+	[ "X${ATCODER_LANG}" = X ] || atcoder_do_switch "$ATCODER_LANG"
+
+	atcoder_assert_git
 	atcoder_assert_pwd
 	atcoder_assert_config
 
-	checked_cp "${WORKROOT}/templates/source/${SOURCETMPL}" "./${SOURCEFILE}"
+	checked_cp_i "${WORKROOT}/templates/source/${SOURCETMPL}" "./${SOURCEFILE}"
+}
+
+atcoder_do_switch() {
+	local ATCODER_LANG="$1"
+	[ "X${ATCODER_LANG}" != X ] || exitm "language is not specified."
+	atcoder_assert_git
+	atcoder_assert_pwd
+
+	case "$ATCODER_LANG" in
+	default)
+		[ ! -e ./.atcoder ] || rm ./.atcoder || exitm "failed to rm ./.atcoder"
+		;;
+	*)
+		checked_cp "${WORKROOT}/templates/config/${ATCODER_LANG}.atcoder" ./.atcoder
+		chmod u+x ./.atcoder || exitm "failed to chmod ./.atcoder"
+		;;
+	esac
+
+	atcoder_load_config
+	atcoder_assert_config
 }
 
 atcoder_do_test() {
@@ -310,6 +349,7 @@ atcoder_do_test() {
 		m "fetching first."
 		atcoder_do_fetch
 	}
+	atcoder_build || exitm "build faield."
 	local SAMPLE_IN SAMPLE_OUT RUN_OUT RC
 	RC=0
 	while read SAMPLE_IN
@@ -332,7 +372,9 @@ atcoder_do_submit() {
 	atcoder_task submit
 }
 
+
 # dispatch
+atcoder_load_config
 SUBCOMMAND="$1"
 shift
 case "$SUBCOMMAND" in
@@ -346,7 +388,10 @@ logout)
 	atcoder_do_logout
 	;;
 init|gen)
-	atcoder_do_init
+	atcoder_do_init "$@"
+	;;
+switch|sw)
+	atcoder_do_switch "$@"
 	;;
 fetch)
 	atcoder_do_fetch
